name = "TgBot"
uuid = "2a22100a-e27d-4393-be66-15413f29656e"
authors = ["Aleksandr Bogdanov <sasha_bogdanov_dev@yahoo.com>"]
version = "0.2.0"

[deps]
ConfigEnv = "01234589-554d-41b7-ae5c-7b6ee2db6796"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Telegram = "1da6f4ae-116c-4c38-8ee9-19974ff3601d"
